services:
  job-orchestrator-core:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - job-orchestrator-net
    volumes:
      - ./:/app
      - core-data:/app/apps/core/data
    command: pnpm --filter core start:dev
    stdin_open: true
    tty: true

  example-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - job-orchestrator-core
    environment:
      CORE_URL: ws://job-orchestrator-core:3000
    networks:
      - job-orchestrator-net
    volumes:
      - ./:/app
    command: pnpm --filter example-service dev
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - job-orchestrator-core
    ports:
      - "5173:5173"
    networks:
      - job-orchestrator-net
    volumes:
      - ./:/app
    command: pnpm --filter frontend dev --host 0.0.0.0
    stdin_open: true
    tty: true

networks:
  job-orchestrator-net:

volumes:
  core-data:
