version: "3.8"

services:
  example-service:
    build:
      context: ../..
      dockerfile: Dockerfile.dev
    environment:
      CORE_URL: ws://job-orchestrator-core:3000
    command: pnpm --filter example-service dev
